### ISSUE TITLE
Created Project Board for Catalyst Innovate

### ISSUE THREAD

**Issue by andreassosilo** [C3ETH/c3eth-innovate#12]
**Tasks:**

- [x] Get access for the Catalyst Innovate repository from @wolstaeb 
- [x] Create project board for Catalyst Innovate
- [x] Move all related issues to project board
- [x] Inform @YanTirta & @wolstaeb about the project board
